#!/bin/sh
#
# @name Quadrotor + Tailsitter
#
# @type VTOL Quad Tailsitter
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default MAV_TYPE 20
#
param set SYS_AUTOSTART 13200
param set CBRK_AIRSPD_CHK 162128
param set CBRK_GPSFAIL 240024
param set CBRK_IO_SAFETY 22027
param set CBRK_VELPOSERR 249916
param set CBRK_ENGINEFAIL 284953
param set CBRK_FLIGHTTERM 121212


param set-default CA_AIRFRAME 4

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.184
param set-default CA_ROTOR0_PY 0.3
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.184
param set-default CA_ROTOR1_PY -0.3
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.184
param set-default CA_ROTOR2_PY -0.3
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.184
param set-default CA_ROTOR3_PY 0.3
param set-default CA_ROTOR3_KM -0.05

param set-default CA_SV_CS_COUNT 0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 0

parm set-default FD_FAIL_R 70

#param set-default FW_P_TC 0.4 #########

#pitch
param set-default FW_PR_FF 0.1 # 0.1
param set-default FW_PR_P 0.3 #
param set-default FW_PR_I 0.3 # 0.3
param set-default FW_PR_D 0


# roll
param set-default FW_RR_FF 0.8 # 0.1
#param set-default FW_RR_P 0.4 # 0.25 #########
param set-default FW_RR_I 0.3 # 0.3
#param set-default FW_RR_D 0.01 #########
param set-default FW_R_RMAX 70
#yaw
param set-default FW_YR_FF 0.2 # 0 make yaw rate controller very weak, only keep default P#############
#param set-default FW_YR_P 0.5 #0.15 ###########
param set-default FW_YR_I 0.1
param set-default FW_YR_D 0
param set-default FW_Y_RMAX 50

param set-default FW_PSP_OFF 5.5 # 0?

param set-default FW_THR_MAX 1 # 1
#param set-default FW_THR_MIN 0.2 ###########
param set-default FW_T_CLMB_MAX 5
param set-default FW_T_HRATE_FF 0.3
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 2

param set-default FW_AIRSPD_STALL 15 #########
param set-default FW_AIRSPD_MIN 19
param set-default FW_AIRSPD_TRIM 20 #########
param set-default FW_AIRSPD_MAX 25

param set-default MC_AIRMODE 0
param set-default MAN_ARM_GESTURE 0.3 # required for yaw airmode
param set-default MC_ROLL_P 3
param set-default MC_PITCH_P 5.5
param set-default MC_ROLLRATE_P 0.259999990463256836
param set-default MC_PITCHRATE_P 0.150000005960464478

param set-default VT_ARSP_TRANS 16
#param set-default VT_B_TRANS_DUR 9 ########
#param set-default VT_FW_DIFTHR_EN 7 #######
param set-default VT_FW_DIFTHR_S_Y 1
#param set-default VT_F_TRANS_DUR 8 #########
param set-default VT_TYPE 0
param set-default WV_EN 0
param set-default FW_WING_SPAN 1.5
# param set-default FW_R_LIM 40 #########

param set-default FW_THR_TRIM 0.2 ####



# This is a test from August 5th. Matching real data values with sim
# parameters in order to find a golden center for control

# param set-default ASPD_BETA_NOISE 0.1499936
 param set-default ASPD_FS_T_STOP 2
 param set-default ASPD_TAS_GATE 4
 param set-default ASPD_WIND_NSD 0.1

 param set-default EKF2_ARSP_THR 10
 param set-default EKF2_DECL_TYPE 3
 param set-default EKF2_GPS_DELAY 110
 param set-default EKF2_GPS_V_NOISE 0.5
 param set-default EKF2_IMU_CTRL 3
# # N/A param set-default EKF2_MAG_YAWLIM 0.2
param set-default EKF2_MULTI_IMU 0
param set-default EKF2_REQ_GPS_H 10
param set-default EKF2_TAS_GATE 3
# # N/A param set-default EKF2_TERR_MASK 3
param set-default EKF2_WIND_NSD 0.01
# # N/A param set-default EV_TSK_RC_LOSS
# # N/A param set-default EV_TSK_STAT_DIS

# param set-default FW_AIRSPD_STALL 15
# param set-default FW_AIRSPD_TRIM 20
# # N/A param set-default FW_ARSP_MODE
param set-default FW_GND_SPD_MIN 5
param set-default FW_MAN_P_MAX 20
param set-default FW_MAN_R_MAX 45
param set-default FW_PN_R_SLEW_MAX 30
param set-default FW_P_LIM_MAX 20
param set-default FW_P_LIM_MIN -20
param set-default FW_P_TC 0.6
param set-default FW_RR_D 0.15
param set-default FW_RR_IMAX 0.2
param set-default FW_RR_P 5.1
param set-default FW_R_LIM 50
param set-default FW_R_TC 0.4 ##
param set-default FW_THR_MIN 0.2
param set-default FW_THR_TRIM 0.2
param set-default FW_WR_IMAX 0.4 #what is it
param set-default FW_YR_FF 0.2 # 0.2
param set-default FW_YR_P 0.5
param set-default VT_ARSP_BLEND 8
# # N/A param set-default VT_B_DEC_FF
param set-default VT_B_DEC_MSS 2
param set-default VT_B_TRANS_DUR 9
param set-default VT_FW_DIFTHR_EN 7
param set-default VT_F_TRANS_DUR 8
param set-default VT_TRANS_MIN_TM 2
param set-default VT_ELEV_MC_LOCK 1
param set-default WEIGHT_BASE 4.4
param set-default WEIGHT_GROSS 4.4
param set-default WV_EN 0

param set-default FW_THR_SLEW_MAX 0.5
param set-default FW_WR_P 0.5
param set-default NAV_ACC_RAD 10
param set-default NPFG_DAMPING 0.75
param set-default NPFG_PERIOD 21
#param set-default NPFG_ROLL_TC 0.9
